version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: dockerfile-api
    ports:
      - "8085:8085"
    networks:
      - sipia_rv1_4
    container_name: transaction-api-con
    hostname: transaction-api
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 50M

networks:
  sipia_rv1_4:
    name: sipia_rv1_4
    driver: bridge
