version: "3.9"

services:
  api:
#    image: davidslatinek/transaction-api:0.9
    build:
      context: .
      dockerfile: dockerfile-api
    ports:
      - "8085:8085"
    networks:
      - sipia_rv1_4
    container_name: transaction-api-con
    hostname: transaction-api
    restart: on-failure

networks:
  sipia_rv1_4:
    name: sipia_rv1_4
    driver: bridge
