version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: dockerfile-db
    ports:
      - "3306:3306"
    volumes:
      - ${HOME}/db/:/var/lib/mysql
    networks:
      - tr
    env_file: .env-db
    container_name: transaction-db-con
    hostname: transaction-db
    restart: on-failure

  api:
    build:
      context: .
      dockerfile: dockerfile-api
    ports:
      - "8085:8085"
    depends_on:
      - db
    networks:
      - tr
    container_name: transaction-api-con
    hostname: transaction-api
    restart: on-failure

networks:
  tr:
    driver: bridge
