version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: dockerfile-db
    ports:
      - "3306:3306"
    volumes:
      - ${HOME}/db/:/var/lib/mysql
    networks:
      - tr
    env_file: .env-db
    container_name: transaction-db-con
    hostname: db
    restart: on-failure

networks:
  tr:
    driver: bridge
