version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: dockerfile-db
    ports:
      - "5000:3306"
    volumes:
      - ${HOME}/transaction-db/:/var/lib/mysql
    networks:
      - sipia_rv1_4
    env_file: .env-db
    container_name: transaction-db-con
    hostname: transaction-db
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 220M

networks:
  sipia_rv1_4:
    name: sipia_rv1_4
    driver: bridge
